; SPDX-License-Identifier: MPL-2.0
; ============================================================
; AgentSkin Installer — NSIS + DuiLib main script
; ============================================================
; Architecture:
;   - No MUI pages. The entire UI is a DuiLib window hosted by
;     AgentSkinUI.dll (plugin/src). NSIS owns install logic only.
;   - .onInit: process cleanup, path decision, payload staging.
;   - Section: wizard loop -> extract -> registry -> finish.
;   - Uninstaller shares this script (un.* functions/section).
;
; Build (from installer/windows/scripts/Build-Installer.ps1):
;   makensis /DVERSION=x.y.z /DUNPACKED=<win-unpacked> AgentSkin.nsi
; ============================================================

Unicode true
SetCompressor /SOLID lzma
SetCompressorDictSize 64
CRCCheck on
XPStyle on

; Allow bare-name includes from include\*.nsh (they reference each
; other without the include\ prefix). NSIS v3.12 does not ship a
; /I command-line switch, so we register the directory here.
!addincludedir "include"

!include "include\config.nsh"
!include "include\log.nsh"
!include "include\path.nsh"
!include "include\safety.nsh"
!include "include\bridge.nsh"
!include "LogicLib.nsh"
!include "FileFunc.nsh"
!include "WinMessages.nsh"

; Payload extraction macro — generated by Build-Installer.ps1
; (scans win-unpacked, emits size-weighted File chunks with
; ASProgress calls between them). Fallback keeps the script
; compilable before the first generation run.
!if FileExists("include\payload.generated.nsh")
  !include "include\payload.generated.nsh"
!else
  !macro PayloadExtract
    !insertmacro ASProgress 90 "Payload not generated — run Build-Installer.ps1"
  !macroend
!endif

; ------------------------------------------------------------
; Installer attributes
; ------------------------------------------------------------
Name "${AS_PRODUCT_NAME}"
OutFile "..\build\${AS_SETUP_NAME}"
InstallDir "$LOCALAPPDATA\Programs\${AS_DIR_NAME}"
RequestExecutionLevel user
ShowInstDetails nevershow
ShowUninstDetails nevershow
BrandingText " "
WindowIcon off
BGGradient off
Icon "..\..\..\assets\branding\icon.ico"
UninstallIcon "..\..\..\assets\branding\icon.ico"

; Version info resource on the setup/uninstall binaries
VIProductVersion "${VERSION}.0"
VIAddVersionKey "ProductName"     "${AS_PRODUCT_NAME}"
VIAddVersionKey "CompanyName"     "${AS_PUBLISHER}"
VIAddVersionKey "FileDescription" "${AS_PRODUCT_NAME} Installer"
VIAddVersionKey "FileVersion"     "${VERSION}"
VIAddVersionKey "ProductVersion"  "${VERSION}"
VIAddVersionKey "LegalCopyright"  "MPL-2.0"

; ------------------------------------------------------------
; Shared state
; ------------------------------------------------------------
Var AS_OPT_DESKTOP      ; 0/1 create desktop shortcut
Var AS_OPT_STARTMENU    ; 0/1 create start-menu shortcut
Var AS_PREV_INSTALL     ; adopted previous install dir ("" = fresh)
Var AS_REMOVE_USERDATA  ; uninstall: 0/1 remove %APPDATA%\AgentSkin

; ============================================================
; INSTALLER
; ============================================================

Function .onInit
  SetShellVarContext current
  Push $0
  Push $1

  ; --- D1: force-kill a running app before touching files ---
  !insertmacro AS_KILL_RUNNING_APP
  Sleep 800
  !insertmacro AS_KILL_RUNNING_APP
  Sleep 400

  ; --- D5: logging ---
  ReadEnvStr $R0 "USERNAME"
  !insertmacro LogMessage "=== Install started ==="
  !insertmacro LogDetail "Product: ${AS_PRODUCT_NAME} v${VERSION} (NSIS+DuiLib)"
  !insertmacro LogMessage "Installer file: $EXEPATH"
  !insertmacro LogDetail "User: $R0"

  ; --- D2: command-line /D= (NSIS already applied it) ---
  Call AgentSkinDetectCommandLineDir

  ; --- D2: previous-install detection (new key, then legacy) ---
  StrCpy $AS_PREV_INSTALL ""
  ReadRegStr $0 HKCU "${AS_INSTALL_REG_KEY}" "InstallLocation"
  ${If} $0 == ""
    ReadRegStr $0 HKCU "${AS_LEGACY_UNINSTALL_KEY}" "InstallLocation"
  ${EndIf}
  ${If} $0 == ""
    ReadRegStr $0 HKLM "${AS_LEGACY_UNINSTALL_KEY}" "InstallLocation"
  ${EndIf}
  ${If} $0 != ""
    StrCpy $R8 $0
    Call AgentSkinExistingInstallPathCanBeAdopted
    ${If} ${Errors}
      !insertmacro LogDetail "Registry path rejected (not adoptable): $0"
    ${Else}
      StrCpy $AS_PREV_INSTALL $R8
      StrCpy $INSTDIR $R8
      !insertmacro LogDetail "Previous install adopted: $AS_PREV_INSTALL"
    ${EndIf}
  ${EndIf}

  ; --- D2: fresh install -> drive scan (unless /D= was given) ---
  ${If} $AS_PREV_INSTALL == ""
    ${GetParameters} $R0
    ClearErrors
    ${GetOptions} $R0 "/D=" $R1
    ${If} ${Errors}
      Call AgentSkinUseFirstAvailableInstallDir
    ${Else}
      !insertmacro LogDetail "User specified /D=$R1, skipping auto-detection"
    ${EndIf}
    ClearErrors
  ${EndIf}

  ; --- D2: normalize (suffix, depth guard) ---
  Call AgentSkinNormalizeInstallDir
  !insertmacro LogDetail "Install dir candidate: $INSTDIR"

  ; --- D1/D4: silent mode never skips validation ---
  ${If} ${Silent}
    Call AgentSkinValidateInstallDir
    ${If} ${Errors}
      !insertmacro LogDetail "SILENT: directory validation FAILED, aborting"
      Quit
    ${EndIf}
  ${EndIf}

  ; --- Stage plugin + skin ($PLUGINSDIR persists until exit) ---
  SetOutPath $PLUGINSDIR
  File "..\plugin\bin\${AS_PLUGIN_DLL}"
  SetOutPath "$PLUGINSDIR\${AS_UI_SUBDIR}\${AS_SKIN_DIRNAME}"
  File /r "..\plugin\ui\${AS_SKIN_DIRNAME}\*.*"

  ; --- Bring up the DuiLib UI thread (skipped in silent mode) ---
  ${IfNot} ${Silent}
    !insertmacro ASBridgeInit "$PLUGINSDIR\${AS_UI_SUBDIR}\${AS_SKIN_DIRNAME}" "install"
  ${EndIf}

  Pop $1
  Pop $0
FunctionEnd

Section "-Main" SEC_MAIN
  Push $0

  ; ----------------------------------------------------------
  ; 1) Wizard loop (skipped in silent mode). The plugin writes
  ;    $INSTDIR + option flags, then we re-validate NSIS-side.
  ; ----------------------------------------------------------
  ${IfNot} ${Silent}
    ${Do}
      AgentSkinUI::ShowWizard "$INSTDIR"
      Pop $R0
      ${If} $R0 == "cancel"
        !insertmacro LogMessage "Install cancelled by user"
        AgentSkinUI::Shutdown
        Pop $R9
        Quit
      ${EndIf}
      ; Packed response: "install|<dir>|<desktop>|<startmenu>". On error,
      ; the plugin pushes "error:<msg>" (no pipe) so the first token is the
      ; whole error. Detect + report before parsing so a corrupted response
      ; can't populate the install state. (Manual prefix check — WordFunc.nsh
      ; is broken in NSIS 3.12.)
      StrCpy $R8 $R0 7
      ${If} $R8 != "install"
        MessageBox MB_ICONSTOP|MB_OK "安装器界面错误：$R0"
        AgentSkinUI::Shutdown
        Pop $R9
        Quit
      ${EndIf}
      !insertmacro ASBridgeSplitWizardResult
      ; $R1=dir, $R2=desktop, $R3=startmenu
      StrCpy $INSTDIR $R1
      StrCpy $AS_OPT_DESKTOP $R2
      StrCpy $AS_OPT_STARTMENU $R3
      !insertmacro LogDetail "Wizard accepted dir: $INSTDIR (desktop=$AS_OPT_DESKTOP startmenu=$AS_OPT_STARTMENU)"
      Call AgentSkinValidateInstallDir
      ${If} ${Errors}
        !insertmacro LogDetail "NSIS-side validation rejected wizard path, re-showing wizard"
        ${Continue}
      ${EndIf}
      ${ExitDo}
    ${Loop}
  ${Else}
    StrCpy $AS_OPT_DESKTOP "1"
    StrCpy $AS_OPT_STARTMENU "1"
  ${EndIf}

  ; ----------------------------------------------------------
  ; 2) Deferred upgrade cleanup (only AFTER the user confirmed)
  ; ----------------------------------------------------------
  ${If} $AS_PREV_INSTALL != ""
    !insertmacro ASProgress 2 "正在清理旧版本…"
    StrCpy $R8 $AS_PREV_INSTALL
    Call AgentSkinRemovePreviousInstall
  ${EndIf}
  !insertmacro AS_KILL_RUNNING_APP
  Sleep 400

  ; ----------------------------------------------------------
  ; 3) Payload (generated chunks with size-weighted progress)
  ; ----------------------------------------------------------
  !insertmacro PayloadExtract

  ; ----------------------------------------------------------
  ; 4) Marker + registry + shortcuts + file associations
  ; ----------------------------------------------------------
  !insertmacro ASProgress 92 "正在写入注册表…"
  Call AgentSkinWriteMarker
  Call AgentSkinDeleteLegacyUninstaller

  WriteRegStr HKCU "${AS_INSTALL_REG_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr HKCU "${AS_INSTALL_REG_KEY}" "Version" "${VERSION}"

  CreateDirectory "$INSTDIR\Uninstall"
  WriteUninstaller "$INSTDIR\Uninstall\Uninstall ${AS_PRODUCT_NAME}.exe"

  ; The uninstaller has no data block: stage the UI runtime next
  ; to it so un.onInit can copy it back into its own $PLUGINSDIR.
  CreateDirectory "$INSTDIR\Uninstall\${AS_UI_SUBDIR}\${AS_SKIN_DIRNAME}"
  CopyFiles "$PLUGINSDIR\${AS_PLUGIN_DLL}" "$INSTDIR\Uninstall\${AS_UI_SUBDIR}"
  CopyFiles "$PLUGINSDIR\${AS_UI_SUBDIR}\${AS_SKIN_DIRNAME}\*.*" "$INSTDIR\Uninstall\${AS_UI_SUBDIR}\${AS_SKIN_DIRNAME}"

  ; Uninstall registry entries (Add/Remove Programs)
  WriteRegStr HKCU "${AS_UNINSTALL_REG_KEY}" "DisplayName" "${AS_PRODUCT_NAME}"
  WriteRegStr HKCU "${AS_UNINSTALL_REG_KEY}" "DisplayVersion" "${VERSION}"
  WriteRegStr HKCU "${AS_UNINSTALL_REG_KEY}" "Publisher" "${AS_PUBLISHER}"
  WriteRegStr HKCU "${AS_UNINSTALL_REG_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr HKCU "${AS_UNINSTALL_REG_KEY}" "DisplayIcon" "$INSTDIR\${AS_PRODUCT_EXE},0"
  WriteRegStr HKCU "${AS_UNINSTALL_REG_KEY}" "UninstallString" '"$INSTDIR\Uninstall\Uninstall ${AS_PRODUCT_NAME}.exe"'
  WriteRegStr HKCU "${AS_UNINSTALL_REG_KEY}" "QuietUninstallString" '"$INSTDIR\Uninstall\Uninstall ${AS_PRODUCT_NAME}.exe" /S'
  WriteRegDWORD HKCU "${AS_UNINSTALL_REG_KEY}" "NoModify" 1
  WriteRegDWORD HKCU "${AS_UNINSTALL_REG_KEY}" "NoRepair" 1
  ${GetSize} "$INSTDIR" "/S=0K" $0 $R8 $R9
  WriteRegDWORD HKCU "${AS_UNINSTALL_REG_KEY}" "EstimatedSize" $0

  ; Shortcuts
  ${If} $AS_OPT_STARTMENU == "1"
    CreateDirectory "$SMPROGRAMS\${AS_PRODUCT_NAME}"
    CreateShortcut "$SMPROGRAMS\${AS_PRODUCT_NAME}\${AS_PRODUCT_NAME}.lnk" "$INSTDIR\${AS_PRODUCT_EXE}" "" "$INSTDIR\${AS_PRODUCT_EXE}" 0
    CreateShortcut "$SMPROGRAMS\${AS_PRODUCT_NAME}\卸载 ${AS_PRODUCT_NAME}.lnk" "$INSTDIR\Uninstall\Uninstall ${AS_PRODUCT_NAME}.exe" "" "$INSTDIR\Uninstall\Uninstall ${AS_PRODUCT_NAME}.exe" 0
  ${EndIf}
  ${If} $AS_OPT_DESKTOP == "1"
    CreateShortcut "$DESKTOP\${AS_PRODUCT_NAME}.lnk" "$INSTDIR\${AS_PRODUCT_EXE}" "" "$INSTDIR\${AS_PRODUCT_EXE}" 0
  ${EndIf}

  ; File associations (.agenttheme / .agentskin-theme / .codex-theme)
  WriteRegStr HKCU "Software\Classes\.agenttheme" "" "AgentSkin.Theme"
  WriteRegStr HKCU "Software\Classes\.agentskin-theme" "" "AgentSkin.Theme"
  WriteRegStr HKCU "Software\Classes\.codex-theme" "" "AgentSkin.Theme"
  WriteRegStr HKCU "Software\Classes\AgentSkin.Theme" "" "AgentSkin Theme"
  WriteRegStr HKCU "Software\Classes\AgentSkin.Theme\DefaultIcon" "" "$INSTDIR\resources\theme-file.ico"
  WriteRegStr HKCU "Software\Classes\AgentSkin.Theme\shell\open\command" "" '"$INSTDIR\${AS_PRODUCT_EXE}" "%1"'

  ; ----------------------------------------------------------
  ; 5) Finish page -> optional launch -> shutdown UI
  ; ----------------------------------------------------------
  !insertmacro ASProgress 100 "安装完成"
  !insertmacro LogMessage "=== Install completed OK ==="
  !insertmacro LogDetail "Install directory: $INSTDIR"

  ${IfNot} ${Silent}
    AgentSkinUI::ShowFinish "install"
    Pop $R0
    AgentSkinUI::Shutdown
    Pop $R9
    ${If} $R0 == "run"
      SetOutPath "$INSTDIR"
      ExecShell "open" "$INSTDIR\${AS_PRODUCT_EXE}"
    ${EndIf}
  ${EndIf}

  Pop $0
SectionEnd

Function .onInstFailed
  !insertmacro LogMessage "=== Install FAILED ==="
  ${IfNot} ${Silent}
    AgentSkinUI::Shutdown
    Pop $R9
  ${EndIf}
FunctionEnd

; ============================================================
; UNINSTALLER
; ============================================================

Function un.onInit
  SetShellVarContext current
  Push $0

  !insertmacro AS_KILL_RUNNING_APP
  Sleep 800

  ReadEnvStr $R0 "USERNAME"
  !insertmacro LogMessage "=== Uninstall started ==="
  !insertmacro LogDetail "Uninstalling from: $INSTDIR"
  !insertmacro LogDetail "User: $R0"

  ; D1: refuse to uninstall a directory we do not own
  Call un.AgentSkinValidateUninstallDir

  ; Stage plugin + skin for the uninstaller's own $PLUGINSDIR
  CreateDirectory "$PLUGINSDIR\${AS_UI_SUBDIR}\${AS_SKIN_DIRNAME}"
  CopyFiles "$INSTDIR\Uninstall\${AS_UI_SUBDIR}\${AS_PLUGIN_DLL}" "$PLUGINSDIR"
  CopyFiles "$INSTDIR\Uninstall\${AS_UI_SUBDIR}\${AS_SKIN_DIRNAME}\*.*" "$PLUGINSDIR\${AS_UI_SUBDIR}\${AS_SKIN_DIRNAME}"

  StrCpy $AS_REMOVE_USERDATA "0"
  ${IfNot} ${Silent}
    !insertmacro ASBridgeInit "$PLUGINSDIR\${AS_UI_SUBDIR}\${AS_SKIN_DIRNAME}" "uninstall"
  ${EndIf}

  Pop $0
FunctionEnd

Section "Uninstall" SEC_UNINSTALL
  ; ----------------------------------------------------------
  ; 1) Confirm page (skipped in silent mode)
  ; ----------------------------------------------------------
  ${IfNot} ${Silent}
    AgentSkinUI::ShowUninstall "$INSTDIR"
    Pop $R0
    ${If} $R0 == "cancel"
      !insertmacro LogMessage "Uninstall cancelled by user"
      AgentSkinUI::Shutdown
      Pop $R9
      Quit
    ${EndIf}
    ; Packed response: "uninstall|<removeUserData>". On error the plugin
    ; pushes "error:<msg>" (no pipe). Same guard pattern as ShowWizard.
    StrCpy $R8 $R0 9
    ${If} $R8 != "uninstall"
      MessageBox MB_ICONSTOP|MB_OK "安装器界面错误：$R0"
      AgentSkinUI::Shutdown
      Pop $R9
      Quit
    ${EndIf}
    !insertmacro ASBridgeSplitUninstallResult
    ; $R1 = removeUserData
    StrCpy $AS_REMOVE_USERDATA $R1
  ${EndIf}

  ; ----------------------------------------------------------
  ; 2) Removal with progress
  ; ----------------------------------------------------------
  !insertmacro ASProgress 15 "正在结束进程…"
  !insertmacro AS_KILL_RUNNING_APP
  Sleep 500

  !insertmacro ASProgress 35 "正在删除程序文件…"
  Call un.AgentSkinRemoveMarker
  Call un.AgentSkinRemoveInstalledFiles

  !insertmacro ASProgress 60 "正在清理快捷方式…"
  Delete "$DESKTOP\${AS_PRODUCT_NAME}.lnk"
  RMDir /r "$SMPROGRAMS\${AS_PRODUCT_NAME}"

  !insertmacro ASProgress 75 "正在清理注册表…"
  Call un.AgentSkinCleanRegistry

  ${If} $AS_REMOVE_USERDATA == "1"
    !insertmacro ASProgress 88 "正在删除用户数据…"
    RMDir /r "${AS_USERDATA_DIR}"
    !insertmacro LogDetail "userData removed: ${AS_USERDATA_DIR}"
  ${EndIf}

  ; ----------------------------------------------------------
  ; 3) Finish page -> shutdown -> self delete
  ; ----------------------------------------------------------
  !insertmacro ASProgress 100 "卸载完成"
  !insertmacro LogMessage "=== Uninstall completed ==="

  ${IfNot} ${Silent}
    AgentSkinUI::ShowFinish "uninstall"
    Pop $R0
    AgentSkinUI::Shutdown
    Pop $R9
  ${EndIf}

  ; Last: remove the uninstaller itself (deferred via PID watcher)
  Delete "$INSTDIR\Uninstall\Uninstall ${AS_PRODUCT_NAME}.exe"
  Call un.AgentSkinScheduleSelfDelete
SectionEnd

Function un.onUninstFailed
  !insertmacro LogMessage "=== Uninstall FAILED ==="
  ${IfNot} ${Silent}
    AgentSkinUI::Shutdown
    Pop $R9
  ${EndIf}
FunctionEnd
