/**
 * build-palette.mjs — Generate palette.css from theme manifest.json
 *
 * Usage:
 *   node scripts/build-palette.mjs [themeId|all]
 *
 * Reads themes/{themeId}/manifest.json (or theme.json), extracts the unified
 * --agentskin-* colors + derived raw values, and outputs a tiny palette.css
 * (~1KB) that defines those custom properties on :root.
 *
 * When the manifest declares `colorSchemes`, each alternative scheme
 * (color-schemes/<id>.json) additionally emits palette.<id>.css so the token
 * source mirrors the per-scheme CSS variants generated by
 * generate-theme-css.mjs.
 *
 * This replaces the 72-file generation step: engines/ provides the shared
 * structure, palette.css provides the per-theme color identity.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
// Note: readFileSync is already imported above; verify mode reuses it.
import { join, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const THEMES_DIR = join(ROOT, 'themes');

/** "r, g, b" string from a hex or rgba() color (border tokens are usually rgba). */
function toRgbTriple(input) {
  const raw = String(input ?? '').trim();
  let m = /^#([0-9a-f]{6})$/i.exec(raw);
  if (m) {
    const n = parseInt(m[1], 16);
    return `${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}`;
  }
  m = /^#([0-9a-f]{3})$/i.exec(raw);
  if (m) {
    const full = m[1].split('').map((c) => c + c).join('');
    const n = parseInt(full, 16);
    return `${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}`;
  }
  m = /^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*[\d.]+\s*)?\)$/i.exec(raw);
  if (m) return `${m[1]}, ${m[2]}, ${m[3]}`;
  return '0, 0, 0';
}

function buildPaletteCss(colors, themeId, meta = {}) {
  const c = colors;
  const lines = [
    `/* palette.css — ${themeId} (${meta.displayName || themeId}) */`,
    `/* Auto-generated from manifest.json — do not edit. */`,
    `:root {`,
    `  --agentskin-bg: ${c.background};`,
    `  --agentskin-surface: ${c.surface};`,
    `  --agentskin-surface-elevated: ${c.surfaceElevated};`,
    `  --agentskin-text: ${c.foreground};`,
    `  --agentskin-muted: ${c.muted};`,
    `  --agentskin-accent: ${c.accent};`,
    `  --agentskin-secondary: ${c.secondary};`,
    `  --agentskin-border: ${c.border || c.accent};`,
    `  --agentskin-code-bg: ${c.codeBackground || c.codeBg || c.background};`,
    `  --agentskin-code-fg: ${c.codeForeground || c.codeFg || c.foreground};`,
    `  --agentskin-focus-ring: ${c.focusRing || `color-mix(in srgb, ${c.accent} 40%, transparent)`};`,
    `  --agentskin-selection: ${c.selection || `color-mix(in srgb, ${c.accent} 32%, transparent)`};`,
    ``,
    `  /* Derived raw RGB values for agents using rgba(var(--raw), alpha) pattern */`,
    `  --agentskin-accent-raw: ${toRgbTriple(c.accent)};`,
    `  --agentskin-secondary-raw: ${toRgbTriple(c.secondary)};`,
    `  --agentskin-text-raw: ${toRgbTriple(c.foreground)};`,
    `  --agentskin-muted-raw: ${toRgbTriple(c.muted)};`,
    `  --agentskin-surface-raw: ${toRgbTriple(c.surface)};`,
    `  --agentskin-surface-elevated-raw: ${toRgbTriple(c.surfaceElevated)};`,
    `  --agentskin-bg-raw: ${toRgbTriple(c.background)};`,
    `  --agentskin-border-raw: ${toRgbTriple(c.border || c.accent)};`,
    `}`,
  ];
  return lines.join('\n') + '\n';
}

function loadManifest(themeDir) {
  // Try manifest.json first, then theme.json
  for (const name of ['manifest.json', 'theme.json']) {
    const p = join(themeDir, name);
    if (existsSync(p)) return JSON.parse(readFileSync(p, 'utf8'));
  }
  return null;
}

function extractColorsFromManifest(manifest) {
  // Manifest format: { colors: { background, surface, ... } }
  // or nested: { theme: { colors: {...} } }
  if (manifest.colors) return manifest.colors;
  if (manifest.theme?.colors) return manifest.theme.colors;
  // Legacy: palette field
  if (manifest.palette) return manifest.palette;
  return null;
}

/** Resolve the full palette set for a theme: [{id, colors, mode}] with the
 *  manifest's own colors first as 'default', then each declared scheme. */
function resolvePalettes(themeDir, manifest, baseColors) {
  const palettes = [{ id: 'default', colors: baseColors }];
  for (const schemeId of manifest.colorSchemes ?? []) {
    const schemePath = join(themeDir, 'color-schemes', `${schemeId}.json`);
    if (!existsSync(schemePath)) continue;
    const scheme = JSON.parse(readFileSync(schemePath, 'utf8'));
    if (scheme.colors) palettes.push({ id: schemeId, colors: scheme.colors });
  }
  return palettes;
}

/** Output filename for a palette id ('default' → palette.css). */
function paletteFileName(id) {
  return id === 'default' ? 'palette.css' : `palette.${id}.css`;
}

function processTheme(themeId) {
  const themeDir = join(THEMES_DIR, themeId);
  if (!existsSync(themeDir)) {
    console.error(`[build-palette] theme dir not found: ${themeDir}`);
    return false;
  }

  const manifest = loadManifest(themeDir);
  if (!manifest) {
    console.error(`[build-palette] no manifest.json/theme.json in ${themeId}`);
    return false;
  }

  const colors = extractColorsFromManifest(manifest);
  if (!colors) {
    console.error(`[build-palette] no colors found in ${themeId} manifest`);
    return false;
  }

  const meta = { displayName: manifest.displayName || manifest.theme?.displayName || themeId };
  for (const palette of resolvePalettes(themeDir, manifest, colors)) {
    const css = buildPaletteCss(palette.colors, themeId, meta);
    const outPath = join(themeDir, paletteFileName(palette.id));
    writeFileSync(outPath, css, 'utf8');
    console.log(`[build-palette] ${themeId}/${palette.id} → ${paletteFileName(palette.id)} (${css.length} bytes)`);
  }
  return true;
}

/**
 * Verify mode: compare generated palette files with the on-disk files.
 * Exits non-zero on staleness so it can gate `npm run check`.
 */
function verifyTheme(themeId) {
  const themeDir = join(THEMES_DIR, themeId);
  if (!existsSync(themeDir)) return true;
  const manifest = loadManifest(themeDir);
  if (!manifest) return true;
  const colors = extractColorsFromManifest(manifest);
  if (!colors) return true;

  const meta = { displayName: manifest.displayName || manifest.theme?.displayName || themeId };
  let ok = true;
  for (const palette of resolvePalettes(themeDir, manifest, colors)) {
    const expected = buildPaletteCss(palette.colors, themeId, meta);
    const fileName = paletteFileName(palette.id);
    const outPath = join(themeDir, fileName);
    if (!existsSync(outPath)) {
      console.error(`[build-palette:verify] ${themeId}: ${fileName} MISSING — run 'npm run generate:palette'`);
      ok = false;
      continue;
    }
    const actual = readFileSync(outPath, 'utf8');
    if (actual !== expected) {
      console.error(`[build-palette:verify] ${themeId}: ${fileName} STALE — run 'npm run generate:palette'`);
      ok = false;
    }
  }
  return ok;
}

// --- Main ---
const args = process.argv.slice(2);
const verifyMode = args.includes('--verify') || args.includes('-v');
const themeArg = args.find((a) => !a.startsWith('-')) || 'all';

if (verifyMode) {
  const dirs = readdirSync(THEMES_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && !d.name.startsWith('_') && !d.name.startsWith('.'))
    .map((d) => d.name);
  let stale = 0;
  for (const id of dirs) {
    if (!verifyTheme(id)) stale++;
  }
  if (stale > 0) {
    console.error(`\n[build-palette:verify] ${stale} palette(s) stale or missing.`);
    process.exit(1);
  }
  console.log(`[build-palette:verify] all ${dirs.length} palette(s) up-to-date.`);
} else if (themeArg === 'all') {
  const dirs = readdirSync(THEMES_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory() && !d.name.startsWith('_') && !d.name.startsWith('.'))
    .map(d => d.name);
  let ok = 0, fail = 0;
  for (const id of dirs) {
    if (processTheme(id)) ok++; else fail++;
  }
  console.log(`\n[build-palette] done: ${ok} ok, ${fail} failed, ${dirs.length} total`);
} else {
  processTheme(themeArg);
}
