// SPDX-License-Identifier: MPL-2.0

/**
 * # check-themes
 *
 * A3 — CI/husky gate for the themes directory. Runs on `themes/**` changes.
 *
 * Checks (beyond the runtime loader's schema validation, which runs in-app):
 *   1. Every `themes/<id>/manifest.json` parses and its `id` matches the
 *      directory name.
 *   2. Every CSS file referenced by `manifest.targets` exists.
 *   3. Each agent CSS declares ALL 14 required `--agentskin-*` tokens
 *      (the same set `scripts/generate-theme-css.mjs` emits — this is the
 *      "14 variables" contract from THEME_SPEC.md). A theme that omits one
 *      renders broken on that agent.
 *   4. `color-scheme` in each agent CSS matches `manifest.mode`
 *      (dark → `color-scheme: dark`, light → `color-scheme: light`).
 *      A mismatch breaks the agent's native UI chrome (scrollbars, form
 *      controls, shadow DOM surfaces) which do not follow CSS variables.
 *   5. `themes/<id>/palette.css` (when present, the generated token source)
 *      also declares the 14 tokens.
 *
 * Exit code is non-zero on any failure so the pre-commit hook blocks.
 */

import fs from 'node:fs/promises';
import path from 'node:path';

const THEMES_DIR = path.resolve(process.cwd(), 'themes');
const ENGINES_DIR = path.resolve(process.cwd(), 'engines');

/** The 14 required design tokens every agent CSS must declare (no hero art —
 *  `--agentskin-art` is injected at runtime, not authored in the theme). */
const REQUIRED_TOKENS = [
  '--agentskin-bg',
  '--agentskin-surface',
  '--agentskin-surface-elevated',
  '--agentskin-text',
  '--agentskin-muted',
  '--agentskin-accent',
  '--agentskin-secondary',
  '--agentskin-border',
  '--agentskin-code-bg',
  '--agentskin-code-fg',
  '--agentskin-focus-ring',
  '--agentskin-selection',
  '--agentskin-button-bg',
  '--agentskin-input-bg',
];

/**
 * Tokens the generated `palette.css` must carry. It is the seed file
 * (written by `scripts/generate-theme-css.mjs`) and only holds the 12 core
 * tokens + `-raw` RGB derivations — `button-bg`/`input-bg` are derived from
 * accent/surface in the per-agent CSS layer, so they are NOT required here.
 */
const PALETTE_TOKENS = REQUIRED_TOKENS.filter(
  (t) => t !== '--agentskin-button-bg' && t !== '--agentskin-input-bg',
);

/**
 * RGB-raw companion tokens — derived in `build-palette.mjs` from their parent
 * color tokens. Per-agent CSS in the engines directory uses
 * `rgba(var(--agentskin-muted-raw), alpha)` for translucent surfaces; if the
 * palette omits the `-raw` token the browser sees an invalid value, collapsing
 * the alpha layer. We require every palette to carry these.
 */
const RAW_TOKENS = [
  '--agentskin-accent-raw',
  '--agentskin-secondary-raw',
  '--agentskin-text-raw',
  '--agentskin-muted-raw',
  '--agentskin-surface-raw',
  '--agentskin-surface-elevated-raw',
  '--agentskin-bg-raw',
  '--agentskin-border-raw',
];

const ALL_PALETTE_TOKENS = [...PALETTE_TOKENS, ...RAW_TOKENS];

/** Detect `var(--x, fallback)` where fallback is hardcoded (e.g. 128,128,128).
 *  These indicate tokens that the palette may not declare, risking silent
 *  fallback drift at runtime. */
function findRawFallbacks(css) {
  const out = [];
  const re = /var\(\s*(--agentskin-[\w-]+)\s*,\s*([^)]+)\)/g;
  let m = re.exec(css);
  while (m !== null) {
    const token = m[1];
    const fallback = m[2].trim();
    // Only flag *-raw with neutral fallback (the known drift pattern)
    if (token.endsWith('-raw') && /128,\s*128,\s*128|#\d\d\d\d\d\d|rgba?\(\s*128/.test(fallback)) {
      out.push(`${token} → fallback ${fallback}`);
    }
    m = re.exec(css);
  }
  return out;
}

function tokenPattern(token) {
  // Match a declaration inside any block: `--agentskin-bg: <value>;`
  return new RegExp(`${token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*:`);
}

async function checkTokenCoverage(cssPath, label, errors, tokens = REQUIRED_TOKENS) {
  let css;
  try {
    css = await fs.readFile(cssPath, 'utf8');
  } catch (e) {
    errors.push(
      `${label}: file not found (${e.message})\n    Fix: Verify the CSS file path exists relative to the theme directory; check for typos in manifest.targets.<agent>.css or ensure the file was generated by npm run generate:theme-css`,
    );
    return;
  }
  const missing = tokens.filter((t) => !tokenPattern(t).test(css));
  if (missing.length > 0) {
    errors.push(
      `${label}: missing ${missing.length} required token(s): ${missing.join(', ')}\n    Fix: Add the missing --agentskin-* variable declarations to the CSS file (e.g. --agentskin-bg: #1a1a1a;) — if this is palette.css, regenerate it with npm run generate:palette`,
    );
  }
  return css;
}

async function main() {
  let dirs;
  try {
    dirs = await fs.readdir(THEMES_DIR, { withFileTypes: true });
  } catch (e) {
    console.error(`check-themes: cannot read themes dir: ${e.message}`);
    process.exit(1);
  }

  const errors = [];
  let checked = 0;

  for (const entry of dirs) {
    if (!entry.isDirectory()) continue;
    if (entry.name === '_shared') continue; // shared layer, not a theme package
    const themeDir = path.join(THEMES_DIR, entry.name);
    const manifestPath = path.join(themeDir, 'manifest.json');

    let manifestRaw;
    try {
      manifestRaw = await fs.readFile(manifestPath, 'utf8');
    } catch {
      continue; // no manifest → not a theme package (e.g. docs/scratch dir)
    }

    let manifest;
    try {
      manifest = JSON.parse(manifestRaw);
    } catch {
      errors.push(
        `${entry.name}: manifest.json is not valid JSON\n    Fix: Open themes/${entry.name}/manifest.json and run it through jsonlint (or a JSON validator) to find and fix syntax errors — common issues: trailing commas, unquoted keys, unescaped characters`,
      );
      continue;
    }

    if (manifest.id !== entry.name) {
      errors.push(
        `${entry.name}: manifest.id "${manifest.id}" != directory name\n    Fix: Change the "id" field in themes/${entry.name}/manifest.json from "${manifest.id}" to "${entry.name}" so it matches the directory name`,
      );
    }
    if (!manifest.colors || typeof manifest.colors.background !== 'string') {
      errors.push(
        `${entry.name}: colors.background missing\n    Fix: Add "colors": { "background": "#<hex>" } to themes/${entry.name}/manifest.json — this is the base background color used to derive the full palette`,
      );
    }
    checked++;

    // 1) target CSS files: existence + token coverage + color-scheme match.
    const targets = manifest.targets ?? {};
    const agentIds = Object.keys(targets);

    // Resolve the scheme list: 'default' (manifest colors) + each declared
    // color scheme (its mode may differ from the manifest mode).
    const schemeIds = ['default', ...(manifest.colorSchemes ?? [])];
    const schemeModes = new Map();
    for (const schemeId of schemeIds) {
      if (schemeId === 'default') {
        schemeModes.set('default', manifest.mode);
        continue;
      }
      try {
        const scheme = JSON.parse(
          await fs.readFile(path.join(themeDir, 'color-schemes', `${schemeId}.json`), 'utf8'),
        );
        schemeModes.set(schemeId, scheme.mode ?? manifest.mode);
      } catch {
        errors.push(
          `${entry.name}: cannot read color-schemes/${schemeId}.json\n    Fix: Create themes/${entry.name}/color-schemes/${schemeId}.json with at least { "mode": "dark" } or { "mode": "light" }, or remove '${schemeId}' from the colorSchemes array in manifest.json if it no longer exists`,
        );
      }
    }

    for (const agentId of agentIds) {
      const config = targets[agentId];
      if (!config || typeof config.css !== 'string') {
        errors.push(
          `${entry.name}: targets.${agentId} missing css path\n    Fix: Add a "css" string field to targets.${agentId} in themes/${entry.name}/manifest.json (e.g. "css": "assets/css/${agentId}.css") pointing to the agent's CSS file`,
        );
        continue;
      }
      // Default scheme CSS lives at the manifest-referenced path (e.g.
      // assets/css/<agent>.css); alternative schemes at assets/css/<schemeId>/<agent>.css.
      for (const schemeId of schemeIds) {
        const cssPath =
          schemeId === 'default'
            ? path.join(themeDir, config.css)
            : path.join(themeDir, 'assets', 'css', schemeId, path.basename(config.css));
        const label = `${entry.name}/${schemeId}/${agentId} (${cssPath})`;
        const css = await checkTokenCoverage(cssPath, label, errors);
        const mode = schemeModes.get(schemeId);
        if (css && mode === 'dark' && !/color-scheme:\s*dark/.test(css)) {
          errors.push(
            `${label}: mode=dark but CSS lacks "color-scheme: dark"\n    Fix: Add "color-scheme: dark;" to the :root or html selector block in the CSS file — without it, native UI chrome (scrollbars, form controls) will render in light mode`,
          );
        }
        if (css && mode === 'light' && !/color-scheme:\s*light/.test(css)) {
          errors.push(
            `${label}: mode=light but CSS lacks "color-scheme: light"\n    Fix: Add "color-scheme: light;" to the :root or html selector block in the CSS file — without it, native UI chrome (scrollbars, form controls) will render in dark mode`,
          );
        }
      }
    }

    // 2) generated palette files (when present) must declare the core tokens.
    for (const schemeId of schemeIds) {
      const paletteName = schemeId === 'default' ? 'palette.css' : `palette.${schemeId}.css`;
      const palettePath = path.join(themeDir, paletteName);
      if (
        (await fs
          .stat(palettePath)
          .then(() => true)
          .catch(() => false)) === true
      ) {
        await checkTokenCoverage(
          palettePath,
          `${entry.name}/${paletteName}`,
          errors,
          ALL_PALETTE_TOKENS,
        );
      }
    }
  }

  // 3) P2 guard: scan engines/*/tokens.css for *-raw fallback to neutral gray.
  //    These indicate defensive fallbacks that exist in engine CSS. They should
  //    never fire when the palette properly declares the *-raw tokens (which
  //    `build-palette.mjs` does). Reported as non-blocking warnings so operators
  //    can see drift observations without CI failure.
  const rawWarnings = [];
  try {
    const engineDirs = await fs.readdir(ENGINES_DIR, { withFileTypes: true });
    for (const ed of engineDirs) {
      if (!ed.isDirectory()) continue;
      const tokensPath = path.join(ENGINES_DIR, ed.name, 'tokens.css');
      let engineCss;
      try {
        engineCss = await fs.readFile(tokensPath, 'utf8');
      } catch {
        continue;
      }
      for (const hit of findRawFallbacks(engineCss)) {
        rawWarnings.push(`engines/${ed.name}/tokens.css: *-raw neutral fallback — ${hit}`);
      }
    }
  } catch {
    // engines/ may not exist in minimal checkouts — non-fatal
  }

  if (rawWarnings.length > 0) {
    console.warn(
      `check-themes: ${rawWarnings.length} *-raw fallback observation(s) (non-blocking):`,
    );
    for (const w of rawWarnings) console.warn(`  ⚠ ${w}`);
  }

  if (errors.length > 0) {
    console.error(`check-themes: ${errors.length} issue(s) in ${checked} theme(s):`);
    for (const e of errors) console.error(`  ✗ ${e}`);
    process.exit(1);
  }
  console.log(`check-themes: OK — ${checked} theme(s) pass (schema+assets+14 tokens+color-scheme)`);
}

main().catch((e) => {
  console.error(`check-themes: unexpected error: ${e.stack ?? e}`);
  process.exit(1);
});
